# Generated by Django 5.0.4 on 2024-04-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=120)),
                ('phonenumber', models.CharField(max_length=100)),
                ('Departement', models.CharField(choices=[('Cp', 'Preparatory Cycle'), ('Cs', 'Super Cycle ')], max_length=2)),
            ],
        ),
    ]
